### ISSUE TITLE
Vehicle spawning code

### ISSUE THREAD

**Issue by Rob-2** [Ghostrider-DbD-/blckeagls-mission-system-v-2.0.2-updated#1]
Hello,
please update the static gun spawning code. At the moment Epoch only loads 1 to EPOCH_VehicleSlotsLimit out of the database. By creating EPOCH_VehicleSlotsLimit+1 you create a slot, that will not be loaded from the database anymore. The problem is, you create a "EPOCH_VehicleSlotsLimit+1" slot, but take the fist slot out of the slotlist for the gun. So maybe a valuable car will get slot "EPOCH_VehicleSlotsLimit+1" later and at the next restart it will not be loaded from the database cause the slot number is greater than EPOCH_VehicleSlotsLimit.

This can be one of the cause of the "my vehicle disappeared at restart" problem.

For handling the VehicleSlotsLimit, see also: http://epochmod.com/forum/index.php?/topic/30983-vehicles-in-mission-staying-after-restart/

In basic it is:
-Don't raise the VehicleSlotsLimit at the moment.
-Check if a free slot is aviable: !(EPOCH_VehicleSlots isEqualTo[])
-Check if the free slot is not reserved for a vehicle at a trader: (count EPOCH_VehicleSlots > EPOCH_storedVehicleCount)

However, I don't think that static guns will need to be saved to the database to survive a restart.

So I would suggest to edit spawnEmplaced.sqf and comment the following lines out:
//So Vehicle doesnt despawn
// EPOCH_VehicleSlotsLimit = EPOCH_VehicleSlotsLimit + 1;
// EPOCH_VehicleSlots pushBack str(EPOCH_VehicleSlotsLimit);
// _slot = EPOCH_VehicleSlots select 0;
// _veh setVariable ['VEHICLE_SLOT',_slot,true];
// EPOCH_VehicleSlots = EPOCH_VehicleSlots - [_slot];
// EPOCH_VehicleSlotCount = count EPOCH_VehicleSlots;
// publicVariable 'EPOCH_VehicleSlotCount';

or delete it. :)

BR
Rob

**Comment by Ghostrider-DbD-** [comment]
Thanks for the feedback. This all makes perfect sense. I will update the github this evening after work.

**Comment by Ghostrider-DbD-** [comment]
BTW, have you tested those changes on your server ?

**Comment by Rob-2** [comment]
I did a quick test on my testserver. Fired up, joined, TPed to a mission and the machine guns were there and standing. But a second test is never wrong, also.  However I think it should be safe. :)

**Comment by Ghostrider-DbD-** [comment]
Both the code fix and initial test report are much appreciated. Just a noob here really, doing some coding in my spare time but it is not my occupation unlike so many who mod for Epoch.

**Comment by Ghostrider-DbD-** [comment]
Both the code fix and initial test report are much appreciated. Just a noob here really, doing some coding in my spare time but it is not my occupation unlike so many who mod for Epoch. I will also look this up when I have a chance, but do you happen to know if:

_veh call EPOCH_server_setVToken;

is necessary to protect a temporary 'vehicle' from deletion by EPOCH cleanup routines ?

**Comment by Rob-2** [comment]
I am not a Pro, too. ;)
Yep, it is.
