### ISSUE TITLE
Esseker Map

### ISSUE THREAD

**Issue by jus61** [Ghostrider-DbD-/blckeagls-mission-system-v-2.0.2-updated#2]
Add this in configOverrides.sqf:

//================================  ESSEKER  ==============================
if (blck_WorldName == "Esseker") then 
{  // 6022.8906,23.348747,17387.381
	blck_SpawnVeh_Major = 3;
	blck_SpawnVeh_Major2 = 2;
	blck_SpawnVeh_Minor = -1;
	blck_SpawnVeh_Minor2 = 1; //1;
	blck_locationBlackList = blck_locationBlackList + [[[6802,0,5187],300],[[10134,0.1,7979],300],[[4014,0,9223],300]];  //  
	diag_log "[DBD Clan] --- >>> Loading config overides for Esseker";
};
//================================  ESSEKER  ==============================

Add this in findWorld.sqf :

//================================  ESSEKER  ==============================
		case "Esseker":{
		diag_log "Esseker-specific settings loaded";
		blck_mapCenter = [6144, 6144, 0]; //centerPosition = {7100, 7750, 300};
		blck_mapRange = 5300;
		if (blck_blacklistSpawns) then {
			blck_locationBlackList = blck_locationBlackList + [[[6802,0,5187],300],[[10134,0.1,7979],300],[[4014,0,9223],300]];
			diag_log "Spawn black list locations added for Esseker";
		};
//================================  ESSEKER  ==============================

**Comment by Ghostrider-DbD-** [comment]
findWorld.sqf updated

**Comment by jus61** [comment]
thx
